# Node.js imajını kullanıyoruz
FROM node:18-alpine

# Konteyner içinde çalışacağımız klasör
WORKDIR /app

# Bağımlılıkları kopyala ve yükle
COPY package.json package-lock.json ./
RUN npm install

# Proje dosyalarının geri kalanını kopyala
COPY . .

# Vite'ın varsayılan portunu dışarı aç
EXPOSE 5173

# Uygulamayı geliştirme modunda (Vite) başlat
CMD ["npm", "run", "dev"]